[project]
name = "leave-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "fastapi[standard]==0.128.7",
    "python-dateutil==2.9.0.post0",
    "python-multipart==0.0.22",
]
